package ru.snowadv.network.stub

import ru.snowadv.network.model.StreamDto
import ru.snowadv.network.model.TopicDto
import ru.snowadv.network.model.UserDto
import ru.snowadv.network.model.UserPresenceDto
import java.time.Instant

internal object StubData {
    private val subscribedStreamsIds = setOf(1L, 2L)
    val streams = listOf(
        StreamDto(1, "general", "desc1", null),
        StreamDto(2, "Development", "desc2", null),
        StreamDto(3, "Design", "desc3", null),
        StreamDto(4, "PR", "desc4", null),
    )
    val subscribedStreams = streams.filter { it.id in subscribedStreamsIds }

    val streamIdToTopicDto = listOf(
        1L to TopicDto(
            "Testing"
        ),
        1L to TopicDto(
            "Bruh"
        ),
        2L to TopicDto(
            "BlahBlahBlah"
        ),
        2L to TopicDto(
            "HihankiDaHahanki"
        ),
        3L to TopicDto(
            "Generic"
        ),
    ).groupBy { it.first }.mapValues { list -> list.value.map { it.second } }

    val emojiMap = mapOf(
        "grinning" to "1f600",
        "smiley" to "1f603",
        "big_smile" to "1f604",
        "grinning_face_with_smiling_eyes" to "1f601",
        "laughing" to "1f606",
        "sweat_smile" to "1f605",
        "rolling_on_the_floor_laughing" to "1f923",
        "joy" to "1f602",
        "smile" to "1f642",
        "upside_down" to "1f643",
        "wink" to "1f609",
        "blush" to "1f60a",
        "innocent" to "1f607",
        "heart_eyes" to "1f60d",
        "heart_kiss" to "1f618",
        "kiss" to "1f617",
        "smiling_face" to "263a",
        "kiss_with_blush" to "1f61a",
        "kiss_smiling_eyes" to "1f619",
        "yum" to "1f60b",
        "stuck_out_tongue" to "1f61b",
        "stuck_out_tongue_wink" to "1f61c",
        "stuck_out_tongue_closed_eyes" to "1f61d",
        "money_face" to "1f911",
        "hug" to "1f917",
        "thinking" to "1f914",
        "silence" to "1f910",
        "neutral" to "1f610",
        "expressionless" to "1f611",
        "speechless" to "1f636",
        "smirk" to "1f60f",
        "unamused" to "1f612",
        "rolling_eyes" to "1f644",
        "grimacing" to "1f62c",
        "lying" to "1f925",
        "relieved" to "1f60c",
        "pensive" to "1f614",
        "sleepy" to "1f62a",
        "drooling" to "1f924",
        "sleeping" to "1f634",
        "cant_talk" to "1f637",
        "sick" to "1f912",
        "hurt" to "1f915",
        "nauseated" to "1f922",
        "sneezing" to "1f927",
        "dizzy" to "1f635",
        "cowboy" to "1f920",
        "sunglasses" to "1f60e",
        "nerd" to "1f913",
        "oh_no" to "1f615",
        "worried" to "1f61f",
        "frown" to "1f641",
        "sad" to "2639",
        "open_mouth" to "1f62e",
        "hushed" to "1f62f",
        "astonished" to "1f632",
        "flushed" to "1f633",
        "frowning" to "1f626",
        "anguished" to "1f627",
        "fear" to "1f628",
        "cold_sweat" to "1f630",
        "exhausted" to "1f625",
        "cry" to "1f622",
        "sob" to "1f62d",
        "scream" to "1f631",
        "confounded" to "1f616",
        "persevere" to "1f623",
        "disappointed" to "1f61e",
        "sweat" to "1f613",
        "weary" to "1f629",
        "anguish" to "1f62b",
        "triumph" to "1f624",
        "rage" to "1f621",
        "angry" to "1f620",
        "smiling_devil" to "1f608",
        "devil" to "1f47f",
        "skull" to "1f480",
        "skull_and_crossbones" to "2620",
        "poop" to "1f4a9",
        "clown" to "1f921",
        "ogre" to "1f479",
        "goblin" to "1f47a",
        "ghost" to "1f47b",
        "alien" to "1f47d",
        "space_invader" to "1f47e",
        "robot" to "1f916",
        "smiley_cat" to "1f63a",
        "smile_cat" to "1f638",
        "joy_cat" to "1f639",
        "heart_eyes_cat" to "1f63b",
        "smirk_cat" to "1f63c",
        "kissing_cat" to "1f63d",
        "scream_cat" to "1f640",
        "crying_cat" to "1f63f",
        "angry_cat" to "1f63e",
        "see_no_evil" to "1f648",
        "hear_no_evil" to "1f649",
        "speak_no_evil" to "1f64a",
        "lipstick_kiss" to "1f48b",
        "love_letter" to "1f48c",
        "cupid" to "1f498",
        "gift_heart" to "1f49d",
        "sparkling_heart" to "1f496",
        "heart_pulse" to "1f497",
        "heartbeat" to "1f493",
        "revolving_hearts" to "1f49e",
        "two_hearts" to "1f495",
        "heart_box" to "1f49f",
        "heart_exclamation" to "2763",
        "broken_heart" to "1f494",
        "heart" to "2764",
        "yellow_heart" to "1f49b",
        "green_heart" to "1f49a",
        "blue_heart" to "1f499",
        "purple_heart" to "1f49c",
        "black_heart" to "1f5a4",
        "100" to "1f4af",
        "anger" to "1f4a2",
        "boom" to "1f4a5",
        "seeing_stars" to "1f4ab",
        "sweat_drops" to "1f4a6",
        "dash" to "1f4a8",
        "hole" to "1f573",
        "bomb" to "1f4a3",
        "umm" to "1f4ac",
        "speech_bubble" to "1f5e8",
        "anger_bubble" to "1f5ef",
        "thought" to "1f4ad",
        "zzz" to "1f4a4",
        "wave" to "1f44b",
        "stop" to "1f91a",
        "high_five" to "1f590",
        "hand" to "270b",
        "spock" to "1f596",
        "ok" to "1f44c",
        "peace_sign" to "270c",
        "fingers_crossed" to "1f91e",
        "rock_on" to "1f918",
        "call_me" to "1f919",
        "point_left" to "1f448",
        "point_right" to "1f449",
        "point_up" to "1f446",
        "middle_finger" to "1f595",
        "point_down" to "1f447",
        "wait_one_second" to "261d",
        "+1" to "1f44d",
        "-1" to "1f44e",
        "fist" to "270a",
        "fist_bump" to "1f44a",
        "left_fist" to "1f91b",
        "right_fist" to "1f91c",
        "clap" to "1f44f",
        "raised_hands" to "1f64c",
        "open_hands" to "1f450",
        "handshake" to "1f91d",
        "pray" to "1f64f",
        "writing" to "270d",
        "nail_polish" to "1f485",
        "selfie" to "1f933",
        "muscle" to "1f4aa",
        "ear" to "1f442",
        "nose" to "1f443",
        "eyes" to "1f440",
        "eye" to "1f441",
        "tongue" to "1f445",
        "lips" to "1f444",
        "baby" to "1f476",
        "boy" to "1f466",
        "girl" to "1f467",
        "man" to "1f468",
        "woman" to "1f469",
        "older_man" to "1f474",
        "older_woman" to "1f475",
        "person_frowning" to "1f64d",
        "person_pouting" to "1f64e",
        "no_signal" to "1f645",
        "ok_signal" to "1f646",
        "information_desk_person" to "1f481",
        "raising_hand" to "1f64b",
        "bow" to "1f647",
        "face_palm" to "1f926",
        "shrug" to "1f937",
        "police" to "1f46e",
        "detective" to "1f575",
        "guard" to "1f482",
        "construction_worker" to "1f477",
        "prince" to "1f934",
        "princess" to "1f478",
        "turban" to "1f473",
        "gua_pi_mao" to "1f472",
        "bride" to "1f470",
        "pregnant" to "1f930",
        "angel" to "1f47c",
        "santa" to "1f385",
        "mother_christmas" to "1f936",
        "massage" to "1f486",
        "haircut" to "1f487",
        "walking" to "1f6b6",
        "running" to "1f3c3",
        "dancer" to "1f483",
        "dancing" to "1f57a",
        "levitating" to "1f574",
        "dancers" to "1f46f",
        "fencing" to "1f93a",
        "horse_racing" to "1f3c7",
        "skier" to "26f7",
        "snowboarder" to "1f3c2",
        "golf" to "1f3cc",
        "surf" to "1f3c4",
        "rowboat" to "1f6a3",
        "swim" to "1f3ca",
        "ball" to "26f9",
        "lift" to "1f3cb",
        "cyclist" to "1f6b4",
        "mountain_biker" to "1f6b5",
        "cartwheel" to "1f938",
        "wrestling" to "1f93c",
        "water_polo" to "1f93d",
        "handball" to "1f93e",
        "juggling" to "1f939",
        "bath" to "1f6c0",
        "in_bed" to "1f6cc",
        "two_women_holding_hands" to "1f46d",
        "man_and_woman_holding_hands" to "1f46b",
        "two_men_holding_hands" to "1f46c",
        "family" to "1f46a",
        "speaking_head" to "1f5e3",
        "silhouette" to "1f464",
        "silhouettes" to "1f465",
        "footprints" to "1f463",
        "tuxedo" to "1f935",
    )

    val randomMessages = listOf(
        "Hi",
        "Hello",
        "How are you?",
        "Test message",
        "Guys, psst, how much are you getting paid?",
        "Guys i accidentally deleted prod db. Where do i get a backup? Do we really have backups or i should bail out?",
    )

    val people = listOf(
        UserDto(
            1,
            "Ivan Ivanov",
            "example@email.com",
            null,
            true
        ),
        UserDto(
            2,
            "Anastasia Petrova",
            "example@email.com",
            null,
            true
        ),
        UserDto(
            3,
            "Sarah Connor",
            "longmailtotesttv@email.com",
            null,
            true
        ),
        UserDto(
            4,
            "Richard Stallman",
            "test@test.com",
            null,
            true
        )
    )

    val currentUser = people.first()

    val serverTimestamp get() = Instant.now().epochSecond

    val peoplePresenceDtosByEmail get() = people.associateBy { it.email }.mapValues {
        UserPresenceDto(
            if (it.value.id % 2L == 0L) "idle" else "active",
            if (it.value.id % 3L == 0L) serverTimestamp-650 else serverTimestamp,
        )
    }

    val peoplePresenceDtosById get() = people.associateBy { it.id.toLong() }.mapValues {
        UserPresenceDto(
            if (it.value.id % 2L == 0L) "idle" else "active",
            if (it.value.id % 3L == 0L) serverTimestamp-650 else serverTimestamp,
        )
    }
}
